eventpad_htmltopdf_preflight_test:
    pattern: /test/{fixture}
    defaults: { _controller: EPHtmlToPdfBundle:Preflight:generateFromFixtures }
eventpad_htmltopdf_preflight_index:
    pattern: /
    defaults: { _controller: EPHtmlToPdfBundle:Preflight:index }