parameters:
    ep_html_to_pdf.converter.class: EP\Bundle\HtmlToPdfBundle\Converter

services:
    ep_html_to_pdf.converter:
        class: %ep_html_to_pdf.converter.class%
        arguments: ["@ep_html_to_pdf.wkhtmltopdf_driver"]
    ep_html_to_pdf.wkhtmltopdf_driver:
        class: EP\Bundle\HtmlToPdfBundle\Drivers\WkHtmlToPdfDriver
        arguments: ["@ep_html_to_pdf.wkhtmltopdf"]
        calls:
            - [setPageMargins, [0,0,0,0]]

    ep_html_to_pdf.wkhtmltopdf:
        class: WkHtmlToPdf

